source 'https://rubygems.org'

# TODO: Have to hardcode full path?
eval_gemfile "/Users/mwoods/hashrocket/exhaust/spec/fixtures/rails_example/Gemfile"

gem 'exhaust', path: "../../../exhaust"
gem 'cucumber'
gem 'capybara-webkit'
gem 'database_cleaner'
gem 'pry'
